services:
  noticeboard:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/dev
    ports:
      - "3000:3000"
    depends_on:
      postgresql:
        condition: service_started
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
  postgresql:
    image: postgres:17
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres -h postgresql
      interval: 5s
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    volumes:
      - dragonflydata:/data
volumes:
  db_data:
  bundle_cache:
  dragonflydata:
  node_modules: